# Generated by Django 6.0.1 on 2026-01-27 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_extraimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category'),
        ),
    ]
