# Generated by Django 6.0.1 on 2026-01-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_depth_product_height_product_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='height',
            new_name='lengh',
        ),
    ]
