# Generated by Django 6.0.1 on 2026-02-20 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_lengh_product_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название модели/группы')),
            ],
            options={
                'verbose_name': 'Группа товаров (Модель)',
                'verbose_name_plural': 'Группы товаров (Модели)',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color_hex',
            field=models.CharField(default='#000000', help_text='HEX код цвета (например, #000000)', max_length=7, verbose_name='Код цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='main.productgroup', verbose_name='Группа товаров (Модель)'),
        ),
    ]
