# Generated by Django 6.0.1 on 2026-03-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productgroup_product_color_hex_product_color_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_images/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка при клике (необязательно)')),
            ],
            options={
                'verbose_name': 'Изображение на главном экране',
                'verbose_name_plural': 'Изображения на главном экране',
                'ordering': ['order', '-id'],
            },
        ),
    ]
